# Generated by Django 6.0.5 on 2026-05-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_partnershiprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="preferred_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("09:00 AM - 10:00 AM", "09:00 AM - 10:00 AM"),
                    ("10:00 AM - 11:00 AM", "10:00 AM - 11:00 AM"),
                    ("11:00 AM - 12:00 PM", "11:00 AM - 12:00 PM"),
                    ("12:00 PM - 01:00 PM", "12:00 PM - 01:00 PM"),
                    ("02:00 PM - 03:00 PM", "02:00 PM - 03:00 PM"),
                    ("03:00 PM - 04:00 PM", "03:00 PM - 04:00 PM"),
                    ("04:00 PM - 05:00 PM", "04:00 PM - 05:00 PM"),
                    ("05:00 PM - 06:00 PM", "05:00 PM - 06:00 PM"),
                    ("06:00 PM - 07:00 PM", "06:00 PM - 07:00 PM"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
